weaviate:
  host: weaviate
  port: 8080
  grpc_port: 50051
  collection_name: documents

ingestion:
  run: False
  path: data/data.csv

embedders:
  hugging_face: 
    model_name: msmarco-MiniLM-L6-cos-v5

postgres:
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  dbname: ${POSTGRES_DB}